#!/usr/bin/env python3
"""
Single script for redirecting to wrapper
"""
from oet.server_client.server import main


# Python entry point
if __name__ == "__main__":
    # Redirecting to the main of server as all the method handling
    # is done there anyway
    main()
