#!/usr/bin/env python3
"""
Single script for redirecting to wrapper
"""

from argparse import ArgumentParser
import importlib
from oet.core.base_calc import CALCULATOR_CLASSES


def parse_otool() -> tuple[str, str, list[str]]:
    """
    Function for parsing otool keywords

    Returns:
    str: Argument for calculator type
    str: Input file name
    list[str]: Remaining arguments parsed by the subclasses
    """
    parser = ArgumentParser(
        prog="otool",
        description="ORCA external tools wrapper.",
        epilog="Commands for individual programs can be obtained by calling <otool method --help>",
    )
    parser.add_argument("inputfile")
    parser.add_argument(
        "method",
        choices=CALCULATOR_CLASSES.keys(),
        help="Type of calculation to execute",
    )
    args, remaining_args = parser.parse_known_args()

    return args.method, args.inputfile, remaining_args


def main():
    """
    Main routine of otools
    """
    # First parse calculator type and cmd arguments
    calc_type, inputfile, args = parse_otool()
    # Get module to be imported and name of class
    import_module, calculator_name = CALCULATOR_CLASSES[calc_type]
    # Import everything
    mod = importlib.import_module(import_module)
    # Get class
    calculator = getattr(mod, calculator_name)
    # Initialize object
    calculator = calculator()
    # Parsing and run the calculation
    inputfile, args, clear_args = calculator.parse_args()
    calculator.run(inputfile=inputfile, args_parsed=args, args_not_parsed=clear_args)


# Python entry point
if __name__ == "__main__":
    main()
